### ISSUE TITLE
Allow use of Jenkins configured installations 

### ISSUE THREAD

**Issue by skyghis** [manahl/recipebuilder#1]
In Jenkins configuration you can add installations instruction about multiple applications like git, jdk, maven, ... 

Theses ready to install versions are very convenient to install prerequisites on builders.
It would be really useful to use theses

E.g.: 

``` yaml
install:
  JDK: Jdk 8u60
  Maven: Maven 3.3.3

script:
  - mvn clean install
  - mvn deploy
```

With theses settings in Jenkins :

![installs](https://cloud.githubusercontent.com/assets/1068552/10218870/970bc2c0-683a-11e5-8fc1-1f6b2e4b8cb8.png)
